### ISSUE TITLE
cElementTree.ParseError

### ISSUE THREAD

**Issue by smhr** [mfouesneau/adsstat#1]
Hi @mfouesneau 

Meanwhile of re-producing your example, after typing

`Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
from papers import Query
import pylab as plt
r = Query('fouesneau')

I get this error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "papers.py", line 230, in __init__
    self._xml = self._query(self._build_query(author))
  File "papers.py", line 299, in _query
    data = ET.parse(f)
  File "<string>", line 62, in parse
  File "<string>", line 38, in parse
cElementTree.ParseError: not well-formed (invalid token): line 33, column 53`

What would be the problem?

Thanks

Mohammad

**Comment by mfouesneau** [comment]
I cannot reproduce the error. Is this still happening or that was a glitch on ads?

**Comment by smhr** [comment]
That was solved. The problem was due to the network problem in my terminal. Sorry for that, but now I get this error:

```python
r.show_word_cloud()
```
```bash
creating the cloud... This may take a while.
Cloud created. Making image...
Done.
```
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "papers.py", line 271, in show_word_cloud
    print(self.worldcloud.words.most_common(20))
AttributeError: 'Query' object has no attribute 'worldcloud'
```
